[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
affineml = "GD8gkSYT3nK3Y5kfNVZBXET98U6PUUrP65eMec7m1az8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
script = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/affineml.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
